pipeClient:pipeClient.c
	gcc $^ -o $@
pipeServer:pipeServer.c
	gcc $^ -o $@
fifo3:fifo3.c
	gcc $^ -o $@
fifo2:fifo2.c
	gcc $^ -o $@
fifo:fifo.c
	gcc $^ -o $@
pipe1:pipe1.c
	gcc $^ -o $@
pipe:pipe.c
	gcc $^ -o $@
